version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "staging"

  - package-ecosystem: "npm"
    directory: "/client" 
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "staging"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "staging"
